import type { NextPage } from 'next';
import Head from 'next/head';
import { format } from 'date-fns';
import ko from 'date-fns/locale/ko';
import LeftSideBar from '@/components/LeftSideBar';
import Table from '@/components/Table';
import Week from '@/components/Week';
import RightSideBar from '@/components/RightSideBar';
import Header from '@/components/Header';

const Home: NextPage = () => {
  const calendarIconLink = () => {
    const todayDayNumber = format(new Date(), 'd', { locale: ko });
    return `https://ssl.gstatic.com/calendar/images/dynamiclogo_2020q4/calendar_${todayDayNumber}_2x.png`;
  };

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Google Calendar Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={calendarIconLink()} />
      </Head>

      <Header />

      <main className="flex flex-row grow min-h-0">
        <div className="basis-64 h-full">
          <LeftSideBar />
        </div>

        <div className="flex flex-col grow h-full">
          <Week />
          <Table />
        </div>

        <RightSideBar />
      </main>
    </div>
  );
};

export default Home;
